### ISSUE TITLE
Apparently not working

### ISSUE THREAD

**Issue by gaesyeah** [ChaosBuffalo/MKCore#107]
Hi! First of all, my english isnt good, so...sorry.

I was really happy when i discovered MKultra was back on development, but when i tried to test it i discovered that now its need some more "dependencies" than before. So i tried to search them in your CurseForge Profile (projects)...And i finded only two of them...So i got here on github and i have finded everything, but there isnt the .jar files (i think), so i managed to do it "manually", even the MKultra and the TargetingAPI. So... it looked good on the start, but it crashed and i discovered that apparently the MKcore have some sort of "problem", i will leave some prints here.

Thanks!
![MKUltra](https://user-images.githubusercontent.com/90418594/136743502-4a824ff5-e79b-436a-b0d3-38f610e764ac.png)

**Comment by Kovak** [comment]
At the moment the test jars are being distributed in our discord: https://discord.gg/rSn5AXHg

The builds were uploaded to curseforge but they won't show projects that only have alpha builds. These builds are currently being used to help construct content for the game, they are not actually suitable for playing. (which is why they were marked alpha)

**Comment by gaesyeah** [comment]
Oh i got it, thanks!
